### ISSUE TITLE
ILS Ansbach - Fehler bei mehrseitigem Fax

### ISSUE THREAD

**Issue by ebelmxi** [OpenFireSource/AlarmWorkflow-Parsers#4]
Nach einem Alarm gestern Nachmittag ist mir zum zweiten mal aufgefallen das der Parser Probleme mit mehrseitigen Faxen hat.
Als Kommentar wurde folgender String erkannt: `Rauchentwicklung am/im Wald - Siehe PIN\nZur Übernahme eines Einsatzes Kontakt mit der ILS aufnehmen!\nMJGSONGESEDäDHHEJ9EEE3EE9BHHEEDEEEEOH]9H9SETDDDODEHEDEDD.#93EHDODD3ED]E09D[E5TEEE35 \nDas Alarmfax darf nur zum internen Dienstgebrauch verwendet werden.\nDer Empfänger hat sicherzustellen, dass unbefugte bzw. nicht beteiligte\nDritte keinen Zugang zu den übermittelten Daten haben - ILS Ansbach -`

Wir nutzen den Parser für die ILS-Ansbach, sind solche Probleme schon bekannt?

**Comment by Flozi95** [comment]
Der Fehler liegt wo anders... Der Parser sucht nach "Ende Fax" das steht da ned drauf ... kann man ausbessern :grin:

**Comment by ebelmxi** [comment]
~~Ist die Suche nach "Ende Fax" Case Sensitive?~~

Edit: Gesucht wird ja nach `if (line.Contains("ENDE FAX"))`

Hier das Fax vom betroffenen Einsatz (Irrelevante Daten entfernt)
![201603231320114133](https://cloud.githubusercontent.com/assets/11402918/14061055/b252199a-f376-11e5-8c4f-fe3b69da90ec.png)

![201603231320114133_2](https://cloud.githubusercontent.com/assets/11402918/14061206/ef683694-f37a-11e5-80f2-11521103c038.png)

**Comment by Flozi95** [comment]
Schau mal bitte in Analysis in die entsprechende txt Datei. Der scheint - aus welchen Gründen auch immer - das Ende Fax komplett zu verschlucken. Das habe ich bis jetzt noch níe beobachtet.

**Comment by ebelmxi** [comment]
Tatsächlich dort fehlt das "Ende Fax" komplett, den Satz darunter liest er jedoch wieder.

```
------------------------------ BEMERKUNG -------------------------------
Rauchentwicklung am/im Wald - Siehe PIN

Zur Übernahme eines Einsatzes Kontakt mit der ILS aufnehmen!

MJGSONGESEDäDHHEJ9EEE3EE9BHHEEDEEEEOH]9H9SETDDDODEHEDEDD.#93EHDODD3ED]E09D[E5TEEE35 
Das Alarmfax darf nur zum internen Dienstgebrauch verwendet werden.
Der Empfänger hat sicherzustellen, dass unbefugte bzw. nicht beteiligte
Dritte keinen Zugang zu den übermittelten Daten haben - ILS Ansbach -
```

Wir haben aktuell AlarmWorkFlow in der Version 0.9.8.0 installiert, wurde da an der Faxverarbeitung etwas geändert? Neue Tesseract kommt ja erst ab 1.1 oder?

**Comment by Flozi95** [comment]
Ob das neue Tesseract da eine Besserung bringt müsste man probieren. :confused:

**Comment by ebelmxi** [comment]
Ich lass das Fax morgen nochmal einlesen, wir haben auch geplant die aktuelle Version zu installieren dann ziehen wir das ein bisschen vor, eventuell nützt es ja.

Ich melde mich dann morgen..

**Comment by Flozi95** [comment]
Bis jetzt ist noch kein Umstieg auf das neue Tesseract gemacht. Müsste man manuell testen/erledigen.
https://github.com/tesseract-ocr/tesseract/wiki/Downloads

**Comment by ebelmxi** [comment]
Ein erneutes einlesen brachte keine Erfolg.

Ich werde das die Tage mal in einer Testumgebung mit der aktuellen Version von Tesseract wiederholen. Soweit erstmal vielen Dank.

**Comment by ebelmxi** [comment]
Wir konnten selbst nicht die aktuelle Version von Tesseract kompilieren, haben jetzt die von hier https://github.com/OpenFireSource/AlarmWorkflow/issues/139 genommen und es wird `ENDE FAX` auch bei zweiseitigen Faxen richtig erkannt.

Sollten doch noch Probleme auftreten werden wir das hier melden.
